<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8SP5G0H" failures="1" tests="1" name="Test" time="3.861" errors="0" timestamp="2025-05-07T21:57:53 IST">
  <testcase classname="testCases.VerifyLoinDataDDT" name="verify_Login" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.DataProviders.getData(DataProviders.java:28)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_Login -->
</testsuite> <!-- Test -->
